### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by svanp** [kiranjyoth/freelancer#1]
I simply extracted the theme in the /sites/all/theme folder on a drupal webhosting. Then I enabled the theme but it just gives a blank page. Mostly this method works with other drupal themes but I guess I need to take some more steps through the process. Can you please give a little hand describing the process? I wanna use CDN method.

**Comment by kiranjyoth** [comment]
I made changes to the template.php, I was using it especially for panel pages. Give it a try now.

Thanks!

**Comment by svanp** [comment]
Now it works, thanks!

2015-07-03 17:52 GMT+02:00 Jyothi K Reddy notifications@github.com:

**Comment by kiranjyoth** [comment]
perfect! closing this issue.
